<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6485db307df34',
	'title' => 'Wop shop',
	'fields' => array(
		array(
			'key' => 'field_6485db300913d',
			'label' => 'Banner',
			'name' => 'banner',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6485de1ff8257',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'product',
						3 => 'acfe-dbt',
						4 => 'acfe-dpt',
						5 => 'acfe-dt',
						6 => 'acfe-dop',
						7 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
						4 => 'product_category',
					),
					'default_value' => 'Carbon High Quality Durable Professional Billiard Pool Cues Stick',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6485de34f8258',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 'Quality construction, materials and finish make these the best house cue option on the market today.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6485de4df8259',
					'label' => 'Redirect link',
					'name' => 'redirect_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_6485de71f825a',
					'label' => 'Photo',
					'name' => 'photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_6485dea1f825c',
					'label' => 'Marquee',
					'name' => 'marquee',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6485deadf825d',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'admin_column_enabled' => 0,
							'admin_column_post_types' => array(
								0 => 'post',
								1 => 'page',
								2 => 'product',
								3 => 'acfe-dbt',
								4 => 'acfe-dpt',
								5 => 'acfe-dt',
								6 => 'acfe-dop',
								7 => 'acfe-form',
							),
							'admin_column_taxonomies' => array(
								0 => 'category',
								1 => 'post_tag',
								2 => 'link_category',
								3 => 'acf-field-group-category',
								4 => 'product_category',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6485dea1f825c',
						),
					),
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6485de86f825b',
			'label' => 'Production best seller',
			'name' => 'production_best_seller',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6485df88f825e',
					'label' => 'Product',
					'name' => 'product',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'post_type' => array(
						0 => 'product',
					),
					'taxonomy' => '',
					'return_format' => 'object',
					'multiple' => 0,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_null' => 0,
					'ui' => 1,
					'save_post_type' => '',
					'parent_repeater' => 'field_6485de86f825b',
				),
			),
		),
		array(
			'key' => 'field_6485dff6f825f',
			'label' => 'Product Category',
			'name' => 'product_category',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6485e1d3f8260',
					'label' => 'Category',
					'name' => 'category',
					'aria-label' => '',
					'type' => 'acfe_taxonomy_terms',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'taxonomy' => array(
						0 => 'product_category',
					),
					'allow_terms' => '',
					'allow_level' => '',
					'field_type' => 'select',
					'default_value' => array(
					),
					'return_format' => 'id',
					'ui' => 1,
					'allow_null' => 0,
					'search_placeholder' => '',
					'multiple' => 0,
					'ajax' => 1,
					'save_terms' => 0,
					'load_terms' => 0,
					'choices' => array(
					),
					'placeholder' => '',
					'layout' => '',
					'toggle' => 0,
					'allow_custom' => 0,
					'other_choice' => 0,
					'parent_repeater' => 'field_6485dff6f825f',
				),
			),
		),
		array(
			'key' => 'field_6485e276f8261',
			'label' => 'Poster',
			'name' => 'poster',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6485e2c9f8262',
					'label' => 'Photo',
					'name' => 'photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'array',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
					'parent_repeater' => 'field_6485e276f8261',
				),
				array(
					'key' => 'field_6485e2dcf8263',
					'label' => 'Redirect link',
					'name' => 'redirect_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_6485e276f8261',
				),
				array(
					'key' => 'field_6485e2eff8264',
					'label' => 'Position',
					'name' => 'position',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => 'The position is determined based on the occurrence of each product category',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6485e276f8261',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/wop-shop.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1686496212,
));

endif;