<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6478c41c4888e',
	'title' => 'Contact',
	'fields' => array(
		array(
			'key' => 'field_6478c41c00f09',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'default_value' => 'E4Y Company - Entertainment For Youth',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6478c49500f0a',
			'label' => 'Description',
			'name' => 'description',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'default_value' => 'Welcome to our contact page. If you have any questions, comments, or requests, please feel free to get in touch using the contact information provided below.',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6478c4cc00f0b',
			'label' => 'Address',
			'name' => 'address',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'acfe-dbt',
				3 => 'acfe-dpt',
				4 => 'acfe-dt',
				5 => 'acfe-dop',
				6 => 'acfe-form',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'acf-field-group-category',
			),
			'default_value' => '18 Nguyen Lam Street, Ward 6, District 10, Ho Chi Minh City, Vietnam',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6478c4dd00f0c',
			'label' => 'Phone number',
			'name' => 'phone_number',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'acfe-dbt',
				3 => 'acfe-dpt',
				4 => 'acfe-dt',
				5 => 'acfe-dop',
				6 => 'acfe-form',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'acf-field-group-category',
			),
			'default_value' => '0707 977 779',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6478c50400f0d',
			'label' => 'email',
			'name' => 'email',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'default_value' => 'info@wop.vn',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/contact-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1686067465,
));

endif;