<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_647f54cd5e8df',
	'title' => 'Productions',
	'fields' => array(
		array(
			'key' => 'field_647f54cd33617',
			'label' => 'Title VIetnamese',
			'name' => 'title_vi',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'product',
			),
			'admin_column_taxonomies' => '',
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_647f55d533618',
			'label' => 'brand',
			'name' => 'brand',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'product',
				3 => 'acfe-dbt',
				4 => 'acfe-dpt',
				5 => 'acfe-dt',
				6 => 'acfe-dop',
				7 => 'acfe-form',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'acf-field-group-category',
				4 => 'product_category',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_647f561a33619',
			'label' => 'redirect_link',
			'name' => 'redirect_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_647f564e3361a',
			'label' => 'Year of manufacture',
			'name' => 'year_of_manufacture',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'product',
				3 => 'acfe-dbt',
				4 => 'acfe-dpt',
				5 => 'acfe-dt',
				6 => 'acfe-dop',
				7 => 'acfe-form',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'acf-field-group-category',
				4 => 'product_category',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1686067405,
));

endif;