<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6478bd221c0e3',
	'title' => 'Joy Billiards',
	'fields' => array(
		array(
			'key' => 'field_6478bd2254f76',
			'label' => 'Banner',
			'name' => 'banner',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478bd4554f77',
					'label' => 'Heading',
					'name' => 'heading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478bd5054f78',
					'label' => 'Sub heading',
					'name' => 'sub_heading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478bd5b54f79',
					'label' => 'Banner',
					'name' => 'banner',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478bd7054f7a',
			'label' => 'About',
			'name' => 'about',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478bd8054f7b',
					'label' => 'First photo',
					'name' => 'first_photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_6478bd9254f7c',
					'label' => 'Second photo',
					'name' => 'second_photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_6478bda554f7d',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'JOY BILLIARD',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478bdb054f7e',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 'JOY BILLIARD was established in 2006 and is known as a leading company in China specializing in the production and supply of billiards-related products.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6478be1754f82',
					'label' => 'JOY Partner',
					'name' => 'joy_partner',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 64,
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478be2754f83',
					'label' => 'Participants',
					'name' => 'participants',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => '80000+',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478be4e54f84',
			'label' => 'Famously know',
			'name' => 'famously_know',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478be5f54f85',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'JOY is also the global leader of the Chinese 8-ball',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478be6954f86',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => '(also known as Heyball)',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478be7554f87',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 'The Joy is famously known for organizing the Heyball Masters tournament, which is the most lucrative cue sports event in the world with a total cash prize of $1.5m and boasts of an enormous cash prize of $730,000 for the winner, attracting athletes from all around the world.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478be8554f88',
			'label' => 'Top Partner',
			'name' => 'top_partner',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478be9354f89',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'E4Y is the first official partner of JOY in Vietnam.',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478bea254f8a',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 'WOP feels fortunate to be the first and only representative in Vietnam to cooperate with JOY BILLIARD\'s development. This is a leading POOL manufacturer in the world famous for the highest-value Heyball tournaments in history. The cooperation aims to elevate the Billiard discipline to a new level and contribute to bringing talented athletes to the world stage. In the future, WOP will also be a place to train and select talented players for JOY BILLIARD - the sponsor that professional players hope to join.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6478beb054f8b',
					'label' => 'Video Url',
					'name' => 'video_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_6478beca54f8c',
					'label' => 'Video thumbnail',
					'name' => 'video_thumbnail',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_6478bee454f8d',
					'label' => 'Photo collection',
					'name' => 'photo_collection',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6478befc54f8e',
							'label' => 'Photo',
							'name' => 'photo',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => 'basic',
							'admin_column_enabled' => 0,
							'admin_column_post_types' => '',
							'admin_column_taxonomies' => '',
							'return_format' => 'url',
							'acfe_thumbnail' => 0,
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
							'library' => 'all',
							'parent_repeater' => 'field_6478bee454f8d',
						),
					),
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/joy-billiards-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1686067484,
));

endif;