<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6478ae106af43',
	'title' => 'About us',
	'fields' => array(
		array(
			'key' => 'field_6478ae10a7c6d',
			'label' => 'About us - WHO WE ARE',
			'name' => 'about_us',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478ae68a7c6e',
					'label' => 'heading',
					'name' => 'heading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'We\'re the first official facility specialized in training professional athletes.',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478ae76a7c6f',
					'label' => 'Small text',
					'name' => 'small_text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'E4Y created the first official facility to train professional athletes and represent Ho Chi Minh City in national tournaments.',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478ae91a7c70',
			'label' => 'Our story',
			'name' => 'our_story',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478aeaba7c71',
					'label' => 'First photo',
					'name' => 'first_photo',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'library' => 'all',
				),
				array(
					'key' => 'field_6478aec2a7c72',
					'label' => 'Second photo',
					'name' => 'second_photo',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'return_format' => 'url',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'library' => 'all',
				),
				array(
					'key' => 'field_6478aed9a7c73',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 'Entertainment for Youth (E4Y) was established in October 2022, to provide billiards entertainment services for young people with the first establishment being World Of Pool (WOP) Billiards Club where located in 18 Nguyen Lam, 6 ward, District 10, HCMC.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478af37a7c77',
			'label' => 'Our mission',
			'name' => 'our_mission',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478aef2a7c74',
					'label' => 'Missions',
					'name' => 'missions',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6478af1ba7c75',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'admin_column_enabled' => 0,
							'admin_column_post_types' => array(
								0 => 'post',
								1 => 'page',
								2 => 'acfe-dbt',
								3 => 'acfe-dpt',
								4 => 'acfe-dt',
								5 => 'acfe-dop',
								6 => 'acfe-form',
							),
							'admin_column_taxonomies' => array(
								0 => 'category',
								1 => 'post_tag',
								2 => 'link_category',
								3 => 'acf-field-group-category',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6478aef2a7c74',
						),
						array(
							'key' => 'field_6478af29a7c76',
							'label' => 'Description',
							'name' => 'description',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'admin_column_enabled' => 0,
							'admin_column_post_types' => '',
							'admin_column_taxonomies' => '',
							'default_value' => '',
							'acfe_textarea_code' => 0,
							'maxlength' => '',
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
							'parent_repeater' => 'field_6478aef2a7c74',
						),
					),
				),
				array(
					'key' => 'field_6478af871dd1e',
					'label' => 'First photo',
					'name' => 'first_photo',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'return_format' => 'url',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'library' => 'all',
				),
				array(
					'key' => 'field_6478af951dd1f',
					'label' => 'Second photo',
					'name' => 'second_photo',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'return_format' => 'url',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'library' => 'all',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478afa922120',
			'label' => 'Partners',
			'name' => 'partners',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6478afbe22121',
					'label' => 'Name',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6478afa922120',
				),
				array(
					'key' => 'field_6478afd622122',
					'label' => 'Redirect link',
					'name' => 'redirect_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_6478afa922120',
				),
				array(
					'key' => 'field_6478afe622123',
					'label' => 'photo',
					'name' => 'photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
					'parent_repeater' => 'field_6478afa922120',
				),
			),
		),
		array(
			'key' => 'field_6478b00f0b050',
			'label' => 'About products',
			'name' => 'about_products',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478b05b0b051',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'Supplying main products JOY',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478b0690b052',
					'label' => 'Redirect link',
					'name' => 'redirect_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/about-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1686067459,
));

endif;