<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_649c50aed2558',
	'title' => 'JOY Production',
	'fields' => array(
		array(
			'key' => 'field_649c515d80f3d',
			'label' => 'Parent page',
			'name' => 'parent_page',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 0,
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'allow_null' => 0,
			'ui' => 1,
			'save_post_type' => '',
		),
		array(
			'key' => 'field_649c521680f3e',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'e-landing-page',
				3 => 'elementor_library',
				4 => 'product',
				5 => 'acfe-dbt',
				6 => 'acfe-dpt',
				7 => 'acfe-dt',
				8 => 'acfe-dop',
				9 => 'acfe-form',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'elementor_library_category',
				4 => 'acf-field-group-category',
				5 => 'product_category',
				6 => 'elementor_font_type',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_649c524680f3f',
			'label' => 'Description',
			'name' => 'description',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_649c525f80f40',
			'label' => 'photo',
			'name' => 'photo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => 'basic',
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'return_format' => 'url',
			'acfe_thumbnail' => 0,
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
			'library' => 'all',
		),
		array(
			'key' => 'field_649c529580f41',
			'label' => 'Product Information',
			'name' => 'product_information',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_649c52a580f42',
			'label' => 'Extra note',
			'name' => 'extra_note',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'e-landing-page',
				3 => 'elementor_library',
				4 => 'product',
				5 => 'acfe-dbt',
				6 => 'acfe-dpt',
				7 => 'acfe-dt',
				8 => 'acfe-dop',
				9 => 'acfe-form',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'elementor_library_category',
				4 => 'acf-field-group-category',
				5 => 'product_category',
				6 => 'elementor_font_type',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_649c52e580f43',
			'label' => 'Product Accessories',
			'name' => 'product_accessories',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_649c531480f44',
					'label' => 'Content',
					'name' => 'content',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'e-landing-page',
						3 => 'elementor_library',
						4 => 'product',
						5 => 'acfe-dbt',
						6 => 'acfe-dpt',
						7 => 'acfe-dt',
						8 => 'acfe-dop',
						9 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'elementor_library_category',
						4 => 'acf-field-group-category',
						5 => 'product_category',
						6 => 'elementor_font_type',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_649c52e580f43',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/joy-product-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1688044410,
));

endif;