<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_64789d39310fc',
	'title' => 'Home page',
	'fields' => array(
		array(
			'key' => 'field_64789d39f1706',
			'label' => 'Top banner',
			'name' => 'top_banner',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_64789d8ef1707',
					'label' => 'Banner Image',
					'name' => 'banner_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_64789e23f1709',
					'label' => 'Marquee',
					'name' => 'marquee',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'layout' => 'table',
					'pagination' => 0,
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6478a4bede76f',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'admin_column_enabled' => 0,
							'admin_column_post_types' => array(
								0 => 'post',
								1 => 'page',
								2 => 'acfe-dbt',
								3 => 'acfe-dpt',
								4 => 'acfe-dt',
								5 => 'acfe-dop',
								6 => 'acfe-form',
							),
							'admin_column_taxonomies' => array(
								0 => 'category',
								1 => 'post_tag',
								2 => 'link_category',
								3 => 'acf-field-group-category',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_64789e23f1709',
						),
					),
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_64789e11f1708',
			'label' => 'About us',
			'name' => 'about_us',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478a239dc311',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'E4Y Company - Entertainment For Youth',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478a24edc312',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 'We was established in October 2022, to provide billiards entertainment services for young people with the first establishment being World Of Pool (WOP) Billia rds Clu b where located in 18 Nguyen Lam, 6 ward, District 10, HCMC.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6478a26cdc313',
					'label' => 'Redirect link',
					'name' => 'redirect_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_6478a299dc314',
					'label' => 'Photo',
					'name' => 'photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_6478aaead0b26',
					'label' => 'Background image',
					'name' => 'background_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'basic',
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'return_format' => 'url',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478a2c0e2e06',
			'label' => 'Our value',
			'name' => 'our_value',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478a2e0e2e07',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => 'Value Of WOP',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478a2ebe2e08',
					'label' => 'Sub title',
					'name' => 'sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => 'The club is a combination of entertainment services and professional competitive training.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6478a306e2e09',
					'label' => 'Values',
					'name' => 'Values',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 1,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6478a37fe2e0a',
							'label' => 'Top title',
							'name' => 'top_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'admin_column_enabled' => 0,
							'admin_column_post_types' => array(
								0 => 'post',
								1 => 'page',
								2 => 'acfe-dbt',
								3 => 'acfe-dpt',
								4 => 'acfe-dt',
								5 => 'acfe-dop',
								6 => 'acfe-form',
							),
							'admin_column_taxonomies' => array(
								0 => 'category',
								1 => 'post_tag',
								2 => 'link_category',
								3 => 'acf-field-group-category',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6478a306e2e09',
						),
						array(
							'key' => 'field_6478a391e2e0b',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'admin_column_enabled' => 0,
							'admin_column_post_types' => array(
								0 => 'post',
								1 => 'page',
								2 => 'acfe-dbt',
								3 => 'acfe-dpt',
								4 => 'acfe-dt',
								5 => 'acfe-dop',
								6 => 'acfe-form',
							),
							'admin_column_taxonomies' => array(
								0 => 'category',
								1 => 'post_tag',
								2 => 'link_category',
								3 => 'acf-field-group-category',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6478a306e2e09',
						),
						array(
							'key' => 'field_6478a39ee2e0c',
							'label' => 'Description',
							'name' => 'description',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'admin_column_enabled' => 0,
							'admin_column_post_types' => '',
							'admin_column_taxonomies' => '',
							'default_value' => '',
							'acfe_textarea_code' => 0,
							'maxlength' => '',
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
							'parent_repeater' => 'field_6478a306e2e09',
						),
						array(
							'key' => 'field_6478a3b1e2e0d',
							'label' => 'Photo',
							'name' => 'photo',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => 'basic',
							'admin_column_enabled' => 0,
							'admin_column_post_types' => '',
							'admin_column_taxonomies' => '',
							'return_format' => 'url',
							'acfe_thumbnail' => 0,
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
							'library' => 'all',
							'parent_repeater' => 'field_6478a306e2e09',
						),
					),
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6478a3cae2e0e',
			'label' => 'More activities',
			'name' => 'more_activities',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6478a3eae2e0f',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'acfe-dbt',
						3 => 'acfe-dpt',
						4 => 'acfe-dt',
						5 => 'acfe-dop',
						6 => 'acfe-form',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'acf-field-group-category',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6478a3f6e2e10',
					'label' => 'Redirect link',
					'name' => 'redirect_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/home-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1686067471,
));

endif;